"""widen_email_text_fields

Revision ID: f8de8784e5a2
Revises: 20260318_0003
Create Date: 2026-03-20 00:15:32.216060
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa




# revision identifiers, used by Alembic.
revision: str = 'f8de8784e5a2'
down_revision: Union[str, Sequence[str], None] = '20260318_0003'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Drop the search vector trigger + function first (they depend on from_address)
    op.execute("DROP TRIGGER IF EXISTS emails_search_vector_trigger ON emails")
    op.execute("DROP FUNCTION IF EXISTS emails_search_vector_update()")

    op.alter_column('emails', 'from_address',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('emails', 'from_name',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('emails', 'reply_to',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=True)
    op.drop_index(op.f('ix_emails_search_vector'), table_name='emails', postgresql_using='gin')

    # Recreate the trigger + function with the new column types
    op.execute("""
        CREATE OR REPLACE FUNCTION emails_search_vector_update() RETURNS trigger AS $$
        BEGIN
            NEW.search_vector :=
                setweight(to_tsvector('english', COALESCE(NEW.subject, '')), 'A') ||
                setweight(to_tsvector('english', COALESCE(NEW.from_name, '')), 'B') ||
                setweight(to_tsvector('english', COALESCE(NEW.from_address, '')), 'B') ||
                setweight(to_tsvector('english', COALESCE(NEW.snippet, '')), 'C');
            RETURN NEW;
        END;
        $$ LANGUAGE plpgsql;
    """)
    op.execute("""
        CREATE TRIGGER emails_search_vector_trigger
        BEFORE INSERT OR UPDATE ON emails
        FOR EACH ROW EXECUTE FUNCTION emails_search_vector_update();
    """)
    op.create_index(op.f('ix_emails_search_vector'), 'emails', ['search_vector'], unique=False, postgresql_using='gin')


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_emails_search_vector'), 'emails', ['search_vector'], unique=False, postgresql_using='gin')
    op.alter_column('emails', 'reply_to',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('emails', 'from_name',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('emails', 'from_address',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    # ### end Alembic commands ###
